[package]
name = "toy_payments_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
serde = { version = "1.0.133", features = ["derive"] }

log = "0.4.0"
env_logger = "0.10.0"
rust_decimal = "1.28.0"
rust_decimal_macros = "1.28.0"
